all: myls mysearch mystat mytail

myls: myls-Gopal.c  
	gcc -o myls myls-Gopal.c  

mysearch: mysearch-Gopal.c 
	gcc -o mysearch mysearch-Gopal.c 

mystat: mystat-Gopal.c 
	gcc -o mystat mystat-Gopal.c 

mytail: mytail-Gopal.c 
	gcc -o mytail mytail-Gopal.c 